-- =========================================
-- Constraints
-- =========================================
-- All primary keys, unique constraints and
-- foreign keys are defined directly in schema.sql.
--
-- This file is reserved for future ALTER TABLE
-- statements if additional constraints are needed.